[2024-01-08T19:06:29.172+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-03-05T00:00:00+00:00 [queued]>
[2024-01-08T19:06:29.265+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-03-05T00:00:00+00:00 [queued]>
[2024-01-08T19:06:29.266+0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-08T19:06:29.516+0300] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2023-03-05 00:00:00+00:00
[2024-01-08T19:06:29.554+0300] {standard_task_runner.py:60} INFO - Started process 30197 to run task
[2024-01-08T19:06:29.654+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'scheduled__2023-03-05T00:00:00+00:00', '--job-id', '1643', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp7cujbqbr']
[2024-01-08T19:06:29.660+0300] {standard_task_runner.py:88} INFO - Job 1643: Subtask get_data
[2024-01-08T19:06:30.699+0300] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data scheduled__2023-03-05T00:00:00+00:00 [running]> on host airflow
[2024-01-08T19:06:31.987+0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-03-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-05T00:00:00+00:00'
[2024-01-08T19:06:31.992+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T19:06:32.021+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_3/scripts/get_data.py']
[2024-01-08T19:06:32.095+0300] {subprocess.py:86} INFO - Output:
[2024-01-08T19:06:33.745+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-08T19:06:33.746+0300] {subprocess.py:93} INFO -   File "/home/angry/mlops_3/scripts/get_data.py", line 9, in <module>
[2024-01-08T19:06:33.747+0300] {subprocess.py:93} INFO -     video = api.search_by_keywords(q=query, search_type=["video"], count=10, limit=30)
[2024-01-08T19:06:33.747+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 1750, in search_by_keywords
[2024-01-08T19:06:33.748+0300] {subprocess.py:93} INFO -     return self.search(
[2024-01-08T19:06:33.748+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 1683, in search
[2024-01-08T19:06:33.749+0300] {subprocess.py:93} INFO -     res_data = self.paged_by_page_token(resource="search", args=args, count=count)
[2024-01-08T19:06:33.749+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 487, in paged_by_page_token
[2024-01-08T19:06:33.749+0300] {subprocess.py:93} INFO -     data = self._parse_response(resp)  # origin response
[2024-01-08T19:06:33.749+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 327, in _parse_response
[2024-01-08T19:06:33.750+0300] {subprocess.py:93} INFO -     raise PyYouTubeException(response)
[2024-01-08T19:06:33.750+0300] {subprocess.py:93} INFO - pyyoutube.error.PyYouTubeException: YouTubeException(status_code=403,message=The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.)
[2024-01-08T19:06:33.893+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-08T19:06:34.096+0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-08T19:06:34.129+0300] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20230305T000000, start_date=20240108T160629, end_date=20240108T160634
[2024-01-08T19:06:34.770+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1643 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 30197)
[2024-01-08T19:06:35.172+0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T19:06:35.293+0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
