[2024-01-08T18:51:08.899+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-07T00:00:00+00:00 [queued]>
[2024-01-08T18:51:08.958+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-07T00:00:00+00:00 [queued]>
[2024-01-08T18:51:08.959+0300] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-08T18:51:09.443+0300] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2023-01-07 00:00:00+00:00
[2024-01-08T18:51:09.459+0300] {standard_task_runner.py:60} INFO - Started process 19883 to run task
[2024-01-08T18:51:09.526+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'scheduled__2023-01-07T00:00:00+00:00', '--job-id', '1554', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpburmsieu']
[2024-01-08T18:51:09.562+0300] {standard_task_runner.py:88} INFO - Job 1554: Subtask get_data
[2024-01-08T18:51:10.230+0300] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data scheduled__2023-01-07T00:00:00+00:00 [running]> on host airflow
[2024-01-08T18:51:11.411+0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-07T00:00:00+00:00'
[2024-01-08T18:51:11.433+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T18:51:11.435+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_3/scripts/get_data.py']
[2024-01-08T18:51:11.507+0300] {subprocess.py:86} INFO - Output:
[2024-01-08T18:51:19.355+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-08T18:51:19.356+0300] {subprocess.py:93} INFO -   File "/home/angry/mlops_3/scripts/get_data.py", line 25, in <module>
[2024-01-08T18:51:19.357+0300] {subprocess.py:93} INFO -     for item in data['items']:
[2024-01-08T18:51:19.358+0300] {subprocess.py:93} INFO - KeyError: 'items'
[2024-01-08T18:51:19.489+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-08T18:51:19.561+0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-08T18:51:19.573+0300] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=get_data, execution_date=20230107T000000, start_date=20240108T155108, end_date=20240108T155119
[2024-01-08T18:51:19.618+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1554 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 19883)
[2024-01-08T18:51:19.637+0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T18:51:19.771+0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
