[2024-01-08T19:11:01.529+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-03-14T00:00:00+00:00 [queued]>
[2024-01-08T19:11:01.589+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-03-14T00:00:00+00:00 [queued]>
[2024-01-08T19:11:01.590+0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-08T19:11:01.718+0300] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2023-03-14 00:00:00+00:00
[2024-01-08T19:11:01.765+0300] {standard_task_runner.py:60} INFO - Started process 33073 to run task
[2024-01-08T19:11:01.794+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'scheduled__2023-03-14T00:00:00+00:00', '--job-id', '1665', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpb2f00pkc']
[2024-01-08T19:11:01.803+0300] {standard_task_runner.py:88} INFO - Job 1665: Subtask get_data
[2024-01-08T19:11:02.637+0300] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data scheduled__2023-03-14T00:00:00+00:00 [running]> on host airflow
[2024-01-08T19:11:03.916+0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-14T00:00:00+00:00'
[2024-01-08T19:11:03.924+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T19:11:03.926+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_3/scripts/get_data.py']
[2024-01-08T19:11:03.974+0300] {subprocess.py:86} INFO - Output:
[2024-01-08T19:11:06.335+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-08T19:11:06.336+0300] {subprocess.py:93} INFO -   File "/home/angry/mlops_3/scripts/get_data.py", line 9, in <module>
[2024-01-08T19:11:06.340+0300] {subprocess.py:93} INFO -     video = api.search_by_keywords(q=query, search_type=["video"], count=10, limit=30)
[2024-01-08T19:11:06.340+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 1750, in search_by_keywords
[2024-01-08T19:11:06.341+0300] {subprocess.py:93} INFO -     return self.search(
[2024-01-08T19:11:06.343+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 1683, in search
[2024-01-08T19:11:06.344+0300] {subprocess.py:93} INFO -     res_data = self.paged_by_page_token(resource="search", args=args, count=count)
[2024-01-08T19:11:06.344+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 487, in paged_by_page_token
[2024-01-08T19:11:06.363+0300] {subprocess.py:93} INFO -     data = self._parse_response(resp)  # origin response
[2024-01-08T19:11:06.364+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 327, in _parse_response
[2024-01-08T19:11:06.364+0300] {subprocess.py:93} INFO -     raise PyYouTubeException(response)
[2024-01-08T19:11:06.364+0300] {subprocess.py:93} INFO - pyyoutube.error.PyYouTubeException: YouTubeException(status_code=403,message=The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.)
[2024-01-08T19:11:06.521+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-08T19:11:06.634+0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-08T19:11:06.646+0300] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20230314T000000, start_date=20240108T161101, end_date=20240108T161106
[2024-01-08T19:11:06.971+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1665 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 33073)
[2024-01-08T19:11:07.107+0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T19:11:07.236+0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
