[2024-01-08T18:42:45.615+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-01-08T18:42:45.677+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-01-08T18:42:45.679+0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-08T18:42:45.769+0300] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2023-01-03 00:00:00+00:00
[2024-01-08T18:42:45.788+0300] {standard_task_runner.py:60} INFO - Started process 14343 to run task
[2024-01-08T18:42:45.805+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'scheduled__2023-01-03T00:00:00+00:00', '--job-id', '1518', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpaoaao3e6']
[2024-01-08T18:42:45.811+0300] {standard_task_runner.py:88} INFO - Job 1518: Subtask get_data
[2024-01-08T18:42:46.944+0300] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data scheduled__2023-01-03T00:00:00+00:00 [running]> on host airflow
[2024-01-08T18:42:48.947+0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-03T00:00:00+00:00'
[2024-01-08T18:42:48.988+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T18:42:49.019+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_3/scripts/get_data.py']
[2024-01-08T18:42:49.281+0300] {subprocess.py:86} INFO - Output:
[2024-01-08T18:42:58.730+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-08T18:42:58.730+0300] {subprocess.py:93} INFO -   File "/home/angry/mlops_3/scripts/get_data.py", line 25, in <module>
[2024-01-08T18:42:58.731+0300] {subprocess.py:93} INFO -     for item in data['items']:
[2024-01-08T18:42:58.746+0300] {subprocess.py:93} INFO - KeyError: 'items'
[2024-01-08T18:42:58.993+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-08T18:42:59.449+0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-08T18:42:59.467+0300] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20230103T000000, start_date=20240108T154245, end_date=20240108T154259
[2024-01-08T18:42:59.584+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1518 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 14343)
[2024-01-08T18:42:59.648+0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T18:43:00.185+0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
