[2024-01-08T19:05:46.902+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-02-16T00:00:00+00:00 [queued]>
[2024-01-08T19:05:47.041+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-02-16T00:00:00+00:00 [queued]>
[2024-01-08T19:05:47.042+0300] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-08T19:05:49.063+0300] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2023-02-16 00:00:00+00:00
[2024-01-08T19:05:49.131+0300] {standard_task_runner.py:60} INFO - Started process 29756 to run task
[2024-01-08T19:05:49.198+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'scheduled__2023-02-16T00:00:00+00:00', '--job-id', '1640', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp1o6dg8rt']
[2024-01-08T19:05:49.229+0300] {standard_task_runner.py:88} INFO - Job 1640: Subtask get_data
[2024-01-08T19:05:50.081+0300] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data scheduled__2023-02-16T00:00:00+00:00 [running]> on host airflow
[2024-01-08T19:05:52.058+0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-02-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-16T00:00:00+00:00'
[2024-01-08T19:05:52.063+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T19:05:52.065+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_3/scripts/get_data.py']
[2024-01-08T19:05:52.142+0300] {subprocess.py:86} INFO - Output:
[2024-01-08T19:05:55.746+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-08T19:05:55.753+0300] {subprocess.py:93} INFO -   File "/home/angry/mlops_3/scripts/get_data.py", line 25, in <module>
[2024-01-08T19:05:55.754+0300] {subprocess.py:93} INFO -     for item in data['items']:
[2024-01-08T19:05:55.755+0300] {subprocess.py:93} INFO - KeyError: 'items'
[2024-01-08T19:05:55.952+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-08T19:05:56.118+0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-08T19:05:56.151+0300] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=get_data, execution_date=20230216T000000, start_date=20240108T160546, end_date=20240108T160556
[2024-01-08T19:05:57.047+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1640 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 29756)
[2024-01-08T19:05:57.130+0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T19:05:57.442+0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
