[2024-01-08T18:46:23.869+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-10T00:00:00+00:00 [queued]>
[2024-01-08T18:46:23.909+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-10T00:00:00+00:00 [queued]>
[2024-01-08T18:46:23.910+0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-08T18:46:23.970+0300] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2023-01-10 00:00:00+00:00
[2024-01-08T18:46:23.992+0300] {standard_task_runner.py:60} INFO - Started process 16687 to run task
[2024-01-08T18:46:24.019+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'scheduled__2023-01-10T00:00:00+00:00', '--job-id', '1535', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpfe44ep22']
[2024-01-08T18:46:24.031+0300] {standard_task_runner.py:88} INFO - Job 1535: Subtask get_data
[2024-01-08T18:46:24.867+0300] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data scheduled__2023-01-10T00:00:00+00:00 [running]> on host airflow
[2024-01-08T18:46:26.299+0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-10T00:00:00+00:00'
[2024-01-08T18:46:26.324+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T18:46:26.361+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_3/scripts/get_data.py']
[2024-01-08T18:46:26.493+0300] {subprocess.py:86} INFO - Output:
[2024-01-08T18:46:35.814+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-08T18:46:35.815+0300] {subprocess.py:93} INFO -   File "/home/angry/mlops_3/scripts/get_data.py", line 25, in <module>
[2024-01-08T18:46:35.815+0300] {subprocess.py:93} INFO -     for item in data['items']:
[2024-01-08T18:46:35.816+0300] {subprocess.py:93} INFO - KeyError: 'items'
[2024-01-08T18:46:36.153+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-08T18:46:36.494+0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-08T18:46:36.519+0300] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20230110T000000, start_date=20240108T154623, end_date=20240108T154636
[2024-01-08T18:46:36.669+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1535 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 16687)
[2024-01-08T18:46:36.789+0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T18:46:37.194+0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
