[2024-01-08T18:42:19.535+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2022-12-31T00:00:00+00:00 [queued]>
[2024-01-08T18:42:19.558+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2022-12-31T00:00:00+00:00 [queued]>
[2024-01-08T18:42:19.559+0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-08T18:42:19.638+0300] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2022-12-31 00:00:00+00:00
[2024-01-08T18:42:19.652+0300] {standard_task_runner.py:60} INFO - Started process 14095 to run task
[2024-01-08T18:42:19.677+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'scheduled__2022-12-31T00:00:00+00:00', '--job-id', '1515', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp37nq0zd6']
[2024-01-08T18:42:19.681+0300] {standard_task_runner.py:88} INFO - Job 1515: Subtask get_data
[2024-01-08T18:42:20.025+0300] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data scheduled__2022-12-31T00:00:00+00:00 [running]> on host airflow
[2024-01-08T18:42:20.514+0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2022-12-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-31T00:00:00+00:00'
[2024-01-08T18:42:20.520+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T18:42:20.524+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_3/scripts/get_data.py']
[2024-01-08T18:42:20.553+0300] {subprocess.py:86} INFO - Output:
[2024-01-08T18:42:27.738+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-08T18:42:27.738+0300] {subprocess.py:93} INFO -   File "/home/angry/mlops_3/scripts/get_data.py", line 25, in <module>
[2024-01-08T18:42:27.743+0300] {subprocess.py:93} INFO -     for item in data['items']:
[2024-01-08T18:42:27.748+0300] {subprocess.py:93} INFO - KeyError: 'items'
[2024-01-08T18:42:27.855+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-08T18:42:27.955+0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-08T18:42:27.974+0300] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20221231T000000, start_date=20240108T154219, end_date=20240108T154227
[2024-01-08T18:42:28.158+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1515 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 14095)
[2024-01-08T18:42:28.225+0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T18:42:28.300+0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
