[2024-01-08T18:51:13.077+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2024-01-08T18:51:13.103+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2024-01-08T18:51:13.104+0300] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-08T18:51:13.142+0300] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2023-01-08 00:00:00+00:00
[2024-01-08T18:51:13.156+0300] {standard_task_runner.py:60} INFO - Started process 19925 to run task
[2024-01-08T18:51:13.166+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'scheduled__2023-01-08T00:00:00+00:00', '--job-id', '1555', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmppunb0qd0']
[2024-01-08T18:51:13.172+0300] {standard_task_runner.py:88} INFO - Job 1555: Subtask get_data
[2024-01-08T18:51:13.455+0300] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data scheduled__2023-01-08T00:00:00+00:00 [running]> on host airflow
[2024-01-08T18:51:14.031+0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-08T00:00:00+00:00'
[2024-01-08T18:51:14.040+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T18:51:14.046+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_3/scripts/get_data.py']
[2024-01-08T18:51:14.102+0300] {subprocess.py:86} INFO - Output:
[2024-01-08T18:51:21.655+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-08T18:51:21.677+0300] {subprocess.py:93} INFO -   File "/home/angry/mlops_3/scripts/get_data.py", line 25, in <module>
[2024-01-08T18:51:21.679+0300] {subprocess.py:93} INFO -     for item in data['items']:
[2024-01-08T18:51:21.679+0300] {subprocess.py:93} INFO - KeyError: 'items'
[2024-01-08T18:51:21.843+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-08T18:51:21.933+0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-08T18:51:21.948+0300] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=get_data, execution_date=20230108T000000, start_date=20240108T155113, end_date=20240108T155121
[2024-01-08T18:51:21.994+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1555 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 19925)
[2024-01-08T18:51:22.033+0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T18:51:22.739+0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
