[2024-01-08T18:39:45.530+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2024-01-08T18:39:46.154+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2024-01-08T18:39:46.373+0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-08T18:39:52.093+0300] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2022-12-26 00:00:00+00:00
[2024-01-08T18:39:52.248+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '1490', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp2x5022sa']
[2024-01-08T18:39:52.268+0300] {standard_task_runner.py:88} INFO - Job 1490: Subtask get_data
[2024-01-08T18:39:52.227+0300] {standard_task_runner.py:60} INFO - Started process 12644 to run task
[2024-01-08T18:40:01.111+0300] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data scheduled__2022-12-26T00:00:00+00:00 [running]> on host airflow
[2024-01-08T18:40:05.521+0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2022-12-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-26T00:00:00+00:00'
[2024-01-08T18:40:05.599+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T18:40:05.640+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_3/scripts/get_data.py']
[2024-01-08T18:40:06.038+0300] {subprocess.py:86} INFO - Output:
[2024-01-08T18:40:18.627+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-08T18:40:18.627+0300] {subprocess.py:93} INFO -   File "/home/angry/mlops_3/scripts/get_data.py", line 25, in <module>
[2024-01-08T18:40:18.628+0300] {subprocess.py:93} INFO -     for item in data['items']:
[2024-01-08T18:40:18.629+0300] {subprocess.py:93} INFO - KeyError: 'items'
[2024-01-08T18:40:18.914+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-08T18:40:21.426+0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-08T18:40:21.872+0300] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20221226T000000, start_date=20240108T153945, end_date=20240108T154021
[2024-01-08T18:40:29.761+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1490 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 12644)
[2024-01-08T18:40:31.067+0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T18:40:34.822+0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
