[2024-01-08T18:58:38.315+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-28T00:00:00+00:00 [queued]>
[2024-01-08T18:58:38.397+0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-28T00:00:00+00:00 [queued]>
[2024-01-08T18:58:38.398+0300] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-08T18:58:39.921+0300] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2023-01-28 00:00:00+00:00
[2024-01-08T18:58:39.996+0300] {standard_task_runner.py:60} INFO - Started process 24737 to run task
[2024-01-08T18:58:40.056+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'scheduled__2023-01-28T00:00:00+00:00', '--job-id', '1598', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpvvpgoc_k']
[2024-01-08T18:58:40.064+0300] {standard_task_runner.py:88} INFO - Job 1598: Subtask get_data
[2024-01-08T18:58:40.824+0300] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data scheduled__2023-01-28T00:00:00+00:00 [running]> on host airflow
[2024-01-08T18:58:42.367+0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-28T00:00:00+00:00'
[2024-01-08T18:58:42.379+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T18:58:42.382+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_3/scripts/get_data.py']
[2024-01-08T18:58:42.482+0300] {subprocess.py:86} INFO - Output:
[2024-01-08T18:58:44.411+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-08T18:58:44.412+0300] {subprocess.py:93} INFO -   File "/home/angry/mlops_3/scripts/get_data.py", line 9, in <module>
[2024-01-08T18:58:44.412+0300] {subprocess.py:93} INFO -     video = api.search_by_keywords(q=query, search_type=["video"], count=10, limit=30)
[2024-01-08T18:58:44.413+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 1750, in search_by_keywords
[2024-01-08T18:58:44.413+0300] {subprocess.py:93} INFO -     return self.search(
[2024-01-08T18:58:44.413+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 1683, in search
[2024-01-08T18:58:44.414+0300] {subprocess.py:93} INFO -     res_data = self.paged_by_page_token(resource="search", args=args, count=count)
[2024-01-08T18:58:44.415+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 487, in paged_by_page_token
[2024-01-08T18:58:44.415+0300] {subprocess.py:93} INFO -     data = self._parse_response(resp)  # origin response
[2024-01-08T18:58:44.415+0300] {subprocess.py:93} INFO -   File "/home/angry/.local/lib/python3.10/site-packages/pyyoutube/api.py", line 327, in _parse_response
[2024-01-08T18:58:44.416+0300] {subprocess.py:93} INFO -     raise PyYouTubeException(response)
[2024-01-08T18:58:44.416+0300] {subprocess.py:93} INFO - pyyoutube.error.PyYouTubeException: YouTubeException(status_code=403,message=The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.)
[2024-01-08T18:58:44.574+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-08T18:58:44.861+0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-08T18:58:44.926+0300] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=get_data, execution_date=20230128T000000, start_date=20240108T155838, end_date=20240108T155844
[2024-01-08T18:58:45.444+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1598 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 24737)
[2024-01-08T18:58:45.567+0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T18:58:45.883+0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
